sudo: required
services:
  - docker

before_install:
  - docker build -t geneblandjr/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run geneblandjr/react-test npm test -- --coverage

after_success:
  - docker build -t geneblandjr/multi-client ./client 
  - docker build -t geneblandjr/multi-nginx ./nginx
  - docker build -t geneblandjr/multi-server ./server
  - docker build -t geneblandjr/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# Take these images and push to docker hub 
  - docker push geneblandjr/multi-client 
  - docker push geneblandjr/multi-nginx 
  - docker push geneblandjr/multi-server 
  - docker push geneblandjr/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-305985142346
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY